AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-node-ems-app

  Sample SAM Template for sam-node-ems-app

  '
Globals:
  Function:
    Timeout: 900
    VpcConfig:
      SecurityGroupIds:
      - sg-09c502d21ea58a914
      SubnetIds:
      - subnet-0d1e198160bb35434
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn:
              Fn::GetAtt:
              - MyAuthFunction
              - Arn
            Identity:
              Headers:
              - authorization
  GetLeaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ems-sam-artifacts/d8697b39a411289a34f9e1c4bcdc799d
      Handler: leaves.getLeaveHandler
      Runtime: nodejs14.x
      Role: arn:aws:iam::877228122437:role/usacademy-lambda-role
      Events:
        GetLeave:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /employee/{id}/leave
            Method: get
  AddLeaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ems-sam-artifacts/d8697b39a411289a34f9e1c4bcdc799d
      Handler: leaves.addLeaveHandler
      Runtime: nodejs14.x
      Role: arn:aws:iam::877228122437:role/usacademy-lambda-role
      Events:
        GetLeave:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /employee/leave
            Method: post
  UpdateLeaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ems-sam-artifacts/d8697b39a411289a34f9e1c4bcdc799d
      Handler: leaves.updateLeaveHandler
      Role: arn:aws:iam::877228122437:role/usacademy-lambda-role
      Runtime: nodejs14.x
      Events:
        GetLeave:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /employee/update-leave/{date}
            Method: put
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ems-sam-artifacts/d8697b39a411289a34f9e1c4bcdc799d
      Handler: authorizer.handler
      Runtime: nodejs14.x

  MyAuthFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ems-sam-artifacts/d8697b39a411289a34f9e1c4bcdc799d
      Handler: authorizer.handler
      Runtime: nodejs14.x
Outputs:
  TeamNodeJsAPI:
    Description: API Gateway endpoint URL for Prod stage for TEAM NODE JS APPLICATION
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
